#! /bin/bash

# Set default log file.
LOG=${1:-/var/log/sipxpbx/sipproxy.log.1}

# Recipients for the report.
RECIPIENTS="interop-config@pingtel.com"

# The temporary file to construct the report in.
REPORT=${TMPDIR:-/tmp}/proxy-summary.$$

(
  hostname -f
  date
  echo

  echo "Log file:"
  ls -l $LOG
  echo

  # Extract the remote host names from the INCOMING lines in the proxy log.
  echo "Remote host values seen:"
  zgrep ':INCOMING:' $LOG |
  sed -e 's/^.*----Remote Host:\(.*\)---- Port: .*$/\1/' |
  # Sort and count the remote hosts seen.
  sort |
  uniq -c |
  sort -nr |
  # Go through the hosts and call dig to find their names.
  while read COUNT ADDR
  do
    if echo "$ADDR" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'
    then
	HOST=$( dig -x $ADDR |
		grep $'\tPTR\t' | 
		grep -v '^;' |
		awk '{ print $5 }' )
    else
	HOST=
    fi
    printf '%7d     %-15s     %s\n' $COUNT "$ADDR" $HOST
  done
  echo

  echo "User-Agent values seen:"
  grep ':INCOMING:' $LOG |
  sed -e '/User-Agent/I!d' \
      -e 's/^.*\\r\\nUser-Agent: *\([^\\]*\)\\r\\n.*$/\1/i' |
  sort |
  uniq -c |
  sort -nr
  echo
) >$REPORT

# Send the report to people.
mail -s "Interop usage summary for $( hostname -f )" $RECIPIENTS <$REPORT

rm $REPORT
