# TODO: Rewrite this whole this according to instructions from here
#  http://sipx-wiki.calivia.com/index.php/Building_ruby-1.8.4_and_ruby-gems

include ../meta/libsrc.mak

all : TODO

TODO :
	@echo "TODO: rewrite according to wiki instructions"
