# TODO: Rewrite this whole this according to instructions from here
#  http://sipx-wiki.calivia.com/index.php/Building_ruby-1.8.4_and_ruby-gems

# Where rpmbuild will do its work.
RPMBUILD_TOPDIR = $(shell rpm --eval '%{_topdir}')

all : TODO

TODO :
	@echo "TODO: rewrite according to wiki intructions"
