<?xml version="1.0" encoding="UTF-8"?>
<definitions name="TestService"
	targetNamespace="urn:TestService" 
	xmlns:tns="urn:TestService" 
	xmlns:xsd1="urn:sipxconfig.xsd" 
	xmlns="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<types>
		<xsd:schema targetNamespace="urn:TestService">
			<xsd:element name="resetUserService">
				<xsd:complexType/>
		    </xsd:element>
		</xsd:schema>
	</types>

	<message name="resetUserServiceResponse">
	</message>
	<message name="resetUserServiceRequest">
	</message>

	<portType name="TestService">
		<operation name="resetUserService">
			<input message="tns:resetUserServiceRequest" name="resetUserServiceRequest"/>
			<output message="tns:resetUserServiceResponse" name="resetUserServiceResponse"/>
		</operation>
	</portType>
	
	<binding name="TestServiceSoapBinding" type="tns:TestService">
		<soap:binding style="document"/>
		<operation name="resetUserService">			
 			<input name="resetUserServiceRequest">
				<soap:body use="literal" namespace="urn:TestService" />
			</input>			
			<output name="resetUserServiceResponse">
				<soap:body use="literal" namespace="urn:TestService"/>
			</output>			
			<soap:operation soapAction=""></soap:operation>			
		</operation>
	</binding>
	
	<service name="TestServiceImplService">
		<port name="TestService" binding="tns:TestServiceSoapBinding">
			<soap:address 
				location="http://localhost:9999/sipxconfig/services/TestService"/>
		</port>
	</service>
	
</definitions>