-- This script creates the Database sequences needed for the PDS.

CREATE SEQUENCE ORG_SEQ;
CREATE SEQUENCE LOG_PHN_SEQ;
CREATE SEQUENCE CONFIG_SET_SEQ;
CREATE SEQUENCE PT_SEQ;
CREATE SEQUENCE REF_PROP_SEQ;
CREATE SEQUENCE CONF_SET_PROPS_SEQ;
CREATE SEQUENCE PHONE_GROUP_SEQ;
CREATE SEQUENCE PHONE_SEQ;
CREATE SEQUENCE MANU_SEQ;
CREATE SEQUENCE CS_PROF_DET_SEQ;
CREATE SEQUENCE RCS_SEQ;
CREATE SEQUENCE CSD_SEQ;
CREATE SEQUENCE USER_SEQ;
CREATE SEQUENCE RP_GROUP_SEQ;
CREATE SEQUENCE EXTENSION_POOLS_SEQ;
CREATE SEQUENCE JOB_SEQ;












