/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sipez_unit_UnitTestActivity */

#ifndef _Included_com_sipez_unit_UnitTestActivity
#define _Included_com_sipez_unit_UnitTestActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_sipez_unit_UnitTestActivity_MESSAGE_LOG_TEXT
#define com_sipez_unit_UnitTestActivity_MESSAGE_LOG_TEXT 1001L
/*
 * Class:     com_sipez_unit_UnitTestActivity
 * Method:    runTests
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sipez_unit_UnitTestActivity_runTests
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
