<?xml version="1.0"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns:tns="urn:StatsService" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:si="http://soapinterop.org/xsd" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/"
  targetNamespace="urn:StatsService">

  <types>
    <xsd:schema targetNamespace="urn:StatsService">
      <xsd:complexType name="ArrayOfBird">
        <xsd:complexContent>
          <xsd:restriction base="SOAP-ENC:Array">
            <xsd:attribute ref="SOAP-ENC:arrayType" arrayType="tns:Bird[]" />
          </xsd:restriction>
        </xsd:complexContent>
      </xsd:complexType>

      <xsd:complexType name="Bird">
        <xsd:sequence>
          <xsd:element name="species" type="xsd:string" minOccurs="1" maxOccurs="1" />
        </xsd:sequence>
      </xsd:complexType>

    </xsd:schema>
  </types>

  <message name="getBirdArrayRequest" />
  <message name="getBirdArrayResponse">
    <part name="getBirdArrayResponse" type="tns:ArrayOfBird" />
  </message>

  <portType name="StatsService">

    <operation name="getBirdArray">
      <input message="tns:getBirdArrayRequest" />
      <output message="tns:getBirdArrayResponse" />
    </operation>

  </portType>

  <binding name="StatsBinding" type="tns:StatsService">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
    
    <operation name="getBirdArray">
      <soap:operation soapAction="urn:StatsService#getBirdArray" style="rpc" />
      <input>
        <soap:body use="encoded" namespace="urn:StatsService"
          encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </input>
      <output>
        <soap:body use="encoded" namespace="urn:StatsService"
          encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </output>
    </operation>

  </binding>

  <service name="StatsImplService">
    <documentation>Realtime Statistics</documentation>
    <port name="StatsService" binding="tns:StatsBinding">
      <soap:address location="http://localhost:2000/" />
    </port>
  </service>
</definitions>