CREATE UNIQUE INDEX PATCH_IDX_ORGANIZATIONS_1 ON ORGANIZATIONS (DNS_DOMAIN);
CREATE UNIQUE INDEX PATCH_IDX_ORGANIZATIONS_2 ON ORGANIZATIONS (NAME);
CREATE UNIQUE INDEX PATCH_IDX_LOGICAL_PHONES_1 ON LOGICAL_PHONES (SHORT_NAME);
CREATE UNIQUE INDEX PATCH_IDX_USERS_1 ON USERS (DISPLAY_ID);




