DELETE FROM CS_PROPERTY_PERMISSIONS
WHERE ref_prop_id IN (SELECT id FROM REF_PROPERTIES WHERE code = 'xp_1020' OR code = 'xp_1019' OR code = 'xp_1018');

DELETE FROM	REF_PROPERTIES
WHERE		CODE = 'xp_1020';

DELETE FROM	REF_PROPERTIES
WHERE		CODE = 'xp_1019';

DELETE FROM	REF_PROPERTIES
WHERE		CODE = 'xp_1018';



