CREATE TABLE JOBS(
ID INTEGER NOT NULL CONSTRAINT PK_JOBS1 PRIMARY KEY,
TYPE INTEGER NOT NULL,
STATUS VARCHAR(1),
START_TIME VARCHAR(30) NOT NULL,
DETAILS VARCHAR(256),
PROGRESS VARCHAR(256),
EXCEPTION_MESSAGE VARCHAR(512));

CREATE SEQUENCE JOB_SEQ;