INSERT INTO	REF_PROPERTIES (	ID, CONTENT, PROFILE_TYPE, NAME, CODE )
VALUES		(1000002,
			'<definition name="PHONESET_HOME_SCREEN_TITLE_PATTERN" mobility="false" cardinality="0..1" description="Title Bar Content"><value name="PHONESET_HOME_SCREEN_TITLE_PATTERN" type="string" cardinality="1" visibility="write" description="Title Bar Content" /></definition>',
			1,
			'PHONESET_HOME_SCREEN_TITLE_PATTERN',
			'xp_1043');

INSERT INTO CS_PROPERTY_PERMISSIONS ( REF_PROP_ID, RCS_ID, IS_READ_ONLY, IS_FINAL )
VALUES ( 1000002, 1, 0, 0 );

INSERT INTO CS_PROPERTY_PERMISSIONS ( REF_PROP_ID, RCS_ID, IS_READ_ONLY, IS_FINAL )
VALUES ( 1000002, 2, 0, 0 );

INSERT INTO CS_PROPERTY_PERMISSIONS ( REF_PROP_ID, RCS_ID, IS_READ_ONLY, IS_FINAL )
VALUES ( 1000002, 3, 0, 0 );

INSERT INTO CS_PROPERTY_PERMISSIONS ( REF_PROP_ID, RCS_ID, IS_READ_ONLY, IS_FINAL )
VALUES ( 1000002, 4, 0, 0 );


INSERT INTO	REF_PROPERTIES (	ID, CONTENT, PROFILE_TYPE, NAME, CODE )
VALUES		(1000003,
			'<definition name="PHONESET_RINGDOWN" mobility="false" cardinality="0..1" description="Ring Down Address"><value name="PHONESET_RINGDOWN" type="string" cardinality="1" visibility="write" description="Ring Down Address" /></definition>',
			1,
			'PHONESET_RINGDOWN',
			'xp_1044');

INSERT INTO CS_PROPERTY_PERMISSIONS ( REF_PROP_ID, RCS_ID, IS_READ_ONLY, IS_FINAL )
VALUES ( 1000003, 1, 0, 0 );

INSERT INTO CS_PROPERTY_PERMISSIONS ( REF_PROP_ID, RCS_ID, IS_READ_ONLY, IS_FINAL )
VALUES ( 1000003, 2, 0, 0 );

INSERT INTO CS_PROPERTY_PERMISSIONS ( REF_PROP_ID, RCS_ID, IS_READ_ONLY, IS_FINAL )
VALUES ( 1000003, 3, 0, 0 );

INSERT INTO CS_PROPERTY_PERMISSIONS ( REF_PROP_ID, RCS_ID, IS_READ_ONLY, IS_FINAL )
VALUES ( 1000003, 4, 0, 0 );

INSERT INTO	REF_PROPERTIES (	ID, CONTENT, PROFILE_TYPE, NAME, CODE )
VALUES		(1000004,
			'<definition name="PHONESET_REMOTE_ID_FORMAT" mobility="false" cardinality="0..1" description="Inbound Caller ID Format"><value name="PHONESET_REMOTE_ID_FORMAT" type="string" cardinality="1" visibility="write" description="Inbound Caller ID Format"/></definition>',
			2,
			'PHONESET_REMOTE_ID_FORMAT',
			'xp_2035');

INSERT INTO CS_PROPERTY_PERMISSIONS ( REF_PROP_ID, RCS_ID, IS_READ_ONLY, IS_FINAL )
VALUES ( 1000004, 1, 0, 0 );

INSERT INTO CS_PROPERTY_PERMISSIONS ( REF_PROP_ID, RCS_ID, IS_READ_ONLY, IS_FINAL )
VALUES ( 1000004, 2, 0, 0 );

INSERT INTO CS_PROPERTY_PERMISSIONS ( REF_PROP_ID, RCS_ID, IS_READ_ONLY, IS_FINAL )
VALUES ( 1000004, 3, 0, 0 );

INSERT INTO CS_PROPERTY_PERMISSIONS ( REF_PROP_ID, RCS_ID, IS_READ_ONLY, IS_FINAL )
VALUES ( 1000004, 4, 0, 0 );
