CREATE TABLE VERSIONS(
APPLIED DATE NOT NULL,
VERSION INTEGER NOT NULL CONSTRAINT PK_VERSIONS1 PRIMARY KEY);

CREATE TABLE PATCHES(
PATCH_NUMBER INTEGER NOT NULL CONSTRAINT PK_PATCHES1 PRIMARY KEY,
DATE_APPLIED DATE NOT NULL,
STATUS VARCHAR(1) NOT NULL,
DESCRIPTION VARCHAR (80));
