// $Id: //depot/OPENDEV/sipXphone/include/pinger/Pinger.h#5 $
// 
// Copyright (C) 2004 SIPfoundry Inc.
// Licensed by SIPfoundry under the LGPL license.
// 
// Copyright (C) 2004 Pingtel Corp.
// Licensed to SIPfoundry under a Contributor Agreement.
// 
// $$
//////////////////////////////////////////////////////////////////////////////

#ifndef _CONFIG_H
#define _CONFIG_H

#ifdef _WIN32
#  define CONFIG_PREFIX_USER_DATA		"..\\meta\\"
#  define CONFIG_PREFIX_SHARED_DATA		"..\\meta\\"
#else
#  error automatically generated by autoconf -- see configure.ac
#endif

#endif
