 --                                                         
 -- File generated by "DeZign for databases"                
 -- Create-date    :12/3/2001                               
 -- Create-time    :2:24:29 PM                              
 -- project-name   :SDS                                     
 -- project-author :John P. Coffey                          
 --                                                         


 -- lower the logging level from NOTICE to WARNING
SET client_min_messages TO warning; 


ALTER TABLE PROFILE_SEQUENCE_NUMS
ADD CONSTRAINT FK_PROFILE_SEQUENCE_NUMS_1 
FOREIGN KEY (CONTEXTS_ID) REFERENCES CONTEXTS (ID)
;


ALTER TABLE ATTRIBUTES
ADD CONSTRAINT FK_ATTRIBUTES_1 
FOREIGN KEY (CTX_ID) REFERENCES CONTEXTS (ID)
;


ALTER TABLE MULTI_ATTRIBUTES
ADD CONSTRAINT FK_MULTI_ATTRIBUTES_1 
FOREIGN KEY (ATTR_ID) REFERENCES ATTRIBUTES (ID)
;

