 --                                                         
 -- File generated by "DeZign for databases"                
 -- Create-date    :12/3/2001                               
 -- Create-time    :2:24:29 PM                              
 -- project-name   :SDS                                     
 -- project-author :John P. Coffey                          
 --                                                         



CREATE TABLE CONTEXTS(
ID INTEGER NOT NULL PRIMARY KEY,
SIP_EXPIRES INTEGER NOT NULL,
SIP_OUTPUT_CSEQ INTEGER DEFAULT 1000 NOT NULL);

COMMENT ON COLUMN CONTEXTS.SIP_OUTPUT_CSEQ IS 'This will eventually go away in favour of the serialized object';

CREATE TABLE PROFILE_SEQUENCE_NUMS(
CONTEXTS_ID INTEGER NOT NULL,
PROFILE_TYPE INTEGER NOT NULL,
SEQUENCE_NUMBER INTEGER NOT NULL,
URL VARCHAR(180),
PRIMARY KEY (CONTEXTS_ID,PROFILE_TYPE));


CREATE TABLE ATTRIBUTES(
ID INTEGER NOT NULL PRIMARY KEY,
CTX_ID INTEGER NOT NULL,
NAME VARCHAR(30) NOT NULL,
VALUE VARCHAR(100) NOT NULL);


CREATE TABLE MULTI_ATTRIBUTES(
ID INTEGER NOT NULL PRIMARY KEY,
ATTR_ID INTEGER,
NAME VARCHAR(30) NOT NULL,
VALUE VARCHAR(100) NOT NULL);

