/*
 * 
 * 
 * Copyright (C) 2005 SIPfoundry Inc.
 * Licensed by SIPfoundry under the LGPL license.
 * 
 * Copyright (C) 2005 Pingtel Corp.
 * Licensed to SIPfoundry under a Contributor Agreement.
 * 
 * $
 */
package org.sipfoundry.sipxconfig.conference;

import org.apache.commons.lang.RandomStringUtils;
import org.sipfoundry.sipxconfig.common.NamedObject;
import org.sipfoundry.sipxconfig.setting.BeanWithSettings;

public class Conference extends BeanWithSettings implements NamedObject {
    public static final String BEAN_NAME = "conferenceConference";

    /**
     * default lengths of autogenerated access code
     */
    public static final int CODE_LEN = 4;
    public static final int SECRET_LEN = 9;

    // settings names
    public static final String ORGANIZER_CODE = "bridge-conference/organizer-code";
    public static final String PARTICIPANT_CODE = "bridge-conference/participant-code";
    public static final String REMOTE_ADMIT_SECRET = "bridge-conference/BOSTON_BRIDGE_CONFERENCE.REMOTE_ADMIT.SECRET";

    private boolean m_enabled;

    private String m_name;

    private String m_description;

    private String m_extension;

    private Bridge m_bridge;

    // trivial get/set
    public String getDescription() {
        return m_description;
    }

    public void setDescription(String description) {
        m_description = description;
    }

    public boolean isEnabled() {
        return m_enabled;
    }

    public void setEnabled(boolean enabled) {
        m_enabled = enabled;
    }

    public String getName() {
        return m_name;
    }

    public void setName(String name) {
        m_name = name;
    }

    public Bridge getBridge() {
        return m_bridge;
    }

    public void setBridge(Bridge bridge) {
        m_bridge = bridge;
    }

    public String getExtension() {
        return m_extension;
    }

    public void setExtension(String extension) {
        m_extension = extension;
    }

    public void generateAccessCodes() {
        setSettingValue(ORGANIZER_CODE, RandomStringUtils.randomNumeric(CODE_LEN));
        setSettingValue(PARTICIPANT_CODE, RandomStringUtils.randomNumeric(CODE_LEN));
    }

    public String getRemoteAdmitSecret() {
        return getSettingValue(REMOTE_ADMIT_SECRET);
    }

    /**
     * It is called by deployment module every time we provision the bridge
     * 
     */
    public void generateRemoteAdmitSecret() {
        setSettingValue(REMOTE_ADMIT_SECRET, RandomStringUtils.randomAlphanumeric(SECRET_LEN));
    }

    public String getOrganizerAccessCode() {
        return getSettingValue(ORGANIZER_CODE);
    }

    public String getParticipantAccessCode() {
        return getSettingValue(PARTICIPANT_CODE);
    }
}
