drop table credential cascade;
drop sequence credential_seq;
drop table line cascade;
drop sequence line_seq;
drop table endpoint cascade;
drop sequence endpoint_seq;
drop table setting cascade;
drop sequence setting_seq;
drop table storage;
drop sequence storage_seq;
