/*
 * Copyright (C) 2006 SIPfoundry Inc.
 * Licensed by SIPfoundry under the LGPL license.
 * 
 * Copyright (C) 2006 Pingtel Corp.
 * Licensed to SIPfoundry under a Contributor Agreement.
 */

/* 
 * Schema for Call Resolver data, including Call State Events (CSE) and
 * Call Detail Records (CDR).
 */


---------------------------------- Versioning ----------------------------------
/*
 * Follow the sipXconfig model for version history
 */

create table version_history(
  version int4 not null primary key,
  applied date not null
);

/**
 * CHANGE VERSION HERE ----------------------------> X <------------------
 *
 * For the initial sipX release with Call Resolver, the database version is 1.
 */
insert into version_history (version, applied) values (1, now());

create table patch(
  name varchar(32) not null primary key
);


---------------------------------- CSE Tables ----------------------------------

/*
 * The call_state_events holds events that describe the lifecycle of a call:
 * call request, call setup, call end or call failure.
 *
 * Values for event_type are
 *   'R' - Call Request, generated by the proxy server when an INVITE request is
 *         received that does not have a tag parameter on the TO field value.
 *   'S' - Call Setup, generated when an ACK is received.
 *   'E' - Call End, generated by any BYE request.
 *   'T' - Call Transfer, generated by an REFER request.
 *   'F' - Call Failure, generated by any 5xx or 6xx response to an INVITE
 *         request, or any 4xx response to an INVITE - except
 *                    
 *           401 Authentication Required
 *           407 Proxy Authentication Required
 *           408 Request timeout
 */
create table call_state_events (
   id              serial8 not null primary key,
   observer        text not null,       /* DNS name of the system that observed the event */
   event_seq       int8 not null,       /* Sequence number of this event at the observer */
   event_time      timestamp not null,  /* Observer (UTC) time when this event occurred */
   event_type      char(1) not null,
   cseq            int4 not null,       /* Value from CSEQ header */ 
   call_id         text not null,       /* Value from SIP Call-Id header */
   from_tag        text,                /* Value from tag attribute of the SIP From header */
   to_tag          text,                /* Value from tag attribute of the SIP To header */
   from_url        text not null,       /* Full From header field value */
   to_url          text not null,       /* Full To header field value */
   contact         text,    /* Contact header field value. For Call Request this is the
                               calling party, for Call Setup this is the called party. */
   refer_to        text,                /* Refer-To header field value */
   referred_by     text,                /* Referred-By header field value */
   failure_status  int2,    /* For Call Failure events, holds 4xx, 5xx, or 6xx status code */
   failure_reason  text     /* For Call Failure events, holds error text */
);


/*
 * The observer_state_events table holds events relating to the event observer
 * state, for example, that the observer has restarted.  The forking proxy
 * and auth proxy are event observers.
 *
 * Status codes:
 *   101 - Observer Reset
 */
create table observer_state_events (
   id              serial8 not null primary key,
   observer        text not null,       /* DNS name of the system that observed the event */
   event_seq       int8 not null,       /* Sequence number of this event at the observer */
   event_time      timestamp not null,  /* Observer (UTC) time when this event occurred */
   status          int2 not null,       /* Status code */
   msg             text                 /* Explanatory message from observer */
);


---------------------------------- CDR Tables ----------------------------------

/* 
 * The parties table holds the SIP address of record (AOR) and contact URL for
 * a party in a SIP call, the caller or callee.
 * AOR example: "Bob <sip:bob@biloxi.com>".
 * Contact example: "<sip:bob@192.0.2.4>".
 * Sometimes we have just the AOR and the contact is null, so we can't put a 
 * not null constraint on the contact column.
 */
create table parties (
  id serial8 not null primary key,
  aor text not null,                    /* SIP AOR */
  contact text,                         /* SIP contact URL */
  unique (aor, contact)
);


/*
 * The cdrs table records info about SIP calls.
 *
 * Start, connect, and end times are nullable to allow for partial CDRs where the
 * call cannot be completely analyzed.  For example, if we can't find a BYE or 
 * any other end event, then the end_time is indeterminate and will be set to NULL.
 * Note that NULL time values work fine with the check constraints declared below,
 * because comparisons return NULL for NULL operands, and a check constraint is
 * satisfied by a NULL value.
 *
 * The termination code column holds an single char value indicating why the call
 * was terminated.  Codes are:
 * 
 *   R: call requested -- got a call_request event, but no other events.
 *   I: call in progress -- got both call_request and call_setup events.
 *   C: successful call completion -- call_request, call_setup, and call_end with
 *      no errors.
 *   F: call failed -- an error occurred.
 */
create table cdrs (
  id serial8 not null primary key,
  call_id text not null,            /* SIP call ID from the INVITE */
  from_tag text not null,           /* SIP from tag provided by caller in the INVITE */
  to_tag text not null,             /* SIP to tag provided by callee in the 200 OK */
  unique (call_id, from_tag, to_tag),
  caller_id int8 not null           /* Caller info: foreign key to parties table */
    references parties (id),
  callee_id int8 not null           /* Callee info: foreign key to parties table */
    references parties (id),
  start_time timestamp,             /* Start time in GMT: initial INVITE received */
  connect_time timestamp,           /* Connect time in GMT: ACK received for 200 OK */
  end_time timestamp,               /* End time in GMT: BYE received, or other ending */
  check (connect_time >= start_time),
  check (end_time >= connect_time),
  termination char(1),              /* Why the call was terminated */
  failure_status int2,              /* SIP error code if the call failed, e.g., 4xx */
  failure_reason text,              /* Text describing the reason for a call failure */
  call_direction char(1)            /* Plugin feature, see below */
);


---------------------------------- Views ----------------------------------

/*
 * Simplify the presentation of CDRs by showing commonly used CDR data in a single
 * view so that the user doesn't have to be confronted with normalization into
 * different tables.
 * Do not include SIP dialog info in the view since it is not of interest for billing,
 * it is only used to link the CDR back to raw CSE data, or for CDR post-processing.
 */

create view view_cdrs as
  select cdr.id, 
         caller.aor as caller_aor, callee.aor as callee_aor,
         start_time, connect_time, end_time,
         termination, failure_status, failure_reason
  from cdrs cdr, parties caller, parties callee
  where cdr.caller_id = caller.id
  and   cdr.callee_id = callee.id;


---------------------------------- Plugins ----------------------------------

/*
 * Call Direction
 */

/*
 * "Call direction" is an application-level plugin. 
 * The purist approach would be to put call direction in its own table, separate 
 * from the cdrs table, but that would be overkill just for a single char(1) column.
 * So this column is in the cdrs table, see above.
 *
 * Call direction is encoded in char(1) as follows: 
 *
 *   Incoming (I): for calls that come in from a PSTN gateway
 *   Outgoing (O): for calls that go out to a PSTN gateway
 *   Intranetwork (A): for calls that are pure SIP and don't go through a gateway
 */

/*
 * Define "view_cdrs_with_call_direction" to be a superset of "view_cdrs" defined 
 * above, with the addition of the call_direction column.
 */

create view view_cdrs_with_call_direction as
  select view_cdr.id, 
         view_cdr.caller_aor, view_cdr.callee_aor,
         view_cdr.start_time, view_cdr.connect_time, view_cdr.end_time,
         view_cdr.termination, view_cdr.failure_status, view_cdr.failure_reason,
         cdr.call_direction
  from view_cdrs view_cdr, cdrs cdr
  where view_cdr.id = cdr.id;
