// $Id: //depot/OPENDEV/sipXphone/src/pingerjni/com_pingtel_DialerHack.cpp#2 $
// 
// Copyright (C) 2004 SIPfoundry Inc.
// Licensed by SIPfoundry under the LGPL license.
// 
// Copyright (C) 2004 Pingtel Corp.
// Licensed to SIPfoundry under a Contributor Agreement.
// 
// $$
//////////////////////////////////////////////////////////////////////////////

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include "pingerjni/org_sipfoundry_DialerHack.h"
#include "os/OsDefs.h"

extern void di(char *str, int toneMs) ;
extern int OffHook() ;
extern int OnHook() ;


/*
 * Class:     org_sipfoundry_DialerHack
 * Method:    Dial
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_sipfoundry_DialerHack_Dial
  (JNIEnv * pEnv, jobject clazz, jstring jsDialString)
{
	char* szDialString = (char*) pEnv->GetStringUTFChars(jsDialString, 0) ;	

//	OnHook() ;
//	OffHook() ;
	di(szDialString, 100) ;

	pEnv->ReleaseStringUTFChars(jsDialString, szDialString) ;
}


/*
 * Class:     org_sipfoundry_DialerHack
 * Method:    OffHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sipfoundry_DialerHack_OffHook
  (JNIEnv * pEnv, jobject clazz)
{

	OffHook() ;
}

/*
 * Class:     org_sipfoundry_DialerHack
 * Method:    OnHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sipfoundry_DialerHack_OnHook
  (JNIEnv * pEnv, jobject clazz)
{

	OnHook() ;
}
